AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  WaterfallBananasService:
    Type: AWS::Serverless::Api
    Description: "Serverless API for CRUD operations"
    Properties:
      Name: "waterfall-bananas-service"
      StageName: Prod
      Auth:
        DefaultAuthorizer: AWS_IAM
        InvokeRole: NONE
      Cors:
        AllowMethods: "'OPTIONS, POST, GET, PUT, DELETE'"
        AllowHeaders: "'Content-Type, x-amz-content-sha256, x-amz-date, X-Amz-Security-Token, Authorization'"
        AllowOrigin: "'FRONTEND_URL'" # replace with frontend URL
        AllowCredentials: true

      # Logging settings
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: "/*"
          HttpMethod: "*"
          MetricsEnabled: true
          DataTraceEnabled: true

  WaterfallBananasFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: bootstrap
      Runtime: provided.al2023
      MemorySize: 512
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref WaterfallBananasTable
      Events:
        BananasOptions:
          Type: Api
          Properties:
            Path: /bananas
            Method: OPTIONS
            RestApiId: !Ref WaterfallBananasService
            Auth:
              Authorizer: NONE
        BananasOptionsId:
          Type: Api
          Properties:
            Path: /bananas/{id}
            Method: OPTIONS
            RestApiId: !Ref WaterfallBananasService
            Auth:
              Authorizer: NONE
        GetBanana:
          Type: Api
          Properties:
            Path: /bananas/{id}
            Method: GET
            RestApiId: !Ref WaterfallBananasService
            
        GetBananas:
          Type: Api
          Properties:
            Path: /bananas
            Method: GET
            RestApiId: !Ref WaterfallBananasService
            
        PutBanana:
          Type: Api
          Properties:
            Path: /bananas
            Method: POST
            RestApiId: !Ref WaterfallBananasService
            
        DeleteBanana:
          Type: Api
          Properties:
            Path: /bananas/{id}
            Method: DELETE
            RestApiId: !Ref WaterfallBananasService
            
        UpdateBanana:
          Type: Api
          Properties:
            Path: /bananas/{id}
            Method: PUT
            RestApiId: !Ref WaterfallBananasService
            
    Metadata:
      BuildMethod: makefile

  WaterfallBananasTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: WaterfallBananas
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
